/**
@credit Tio
@cek khodam
**/

let handler = async (m, {conn}) => {

let who = m.mentionedJid[0] ? m.mentionedJid[0] : m.quoted ? m.quoted.sender : m.sender

const khodam = [
    "Khodam Harimau Bangkit",
    "Khodam Macan Terbang",
    "Khodam Singa Perkasa",
    "Khodam Naga Tersembunyi",
    "Khodam Garuda Perkasa",
    "Khodam Phoenix Bersinar",
    "Khodam Unicorn Gemilang",
    "Khodam Griffin Terbang",
    "Khodam Pegasus Terbang",
    "Khodam Sphinx Tertawa",
    "Khodam Centaur Cerdik",
    "Khodam Feniks Agung",
    "Khodam Cerberus Setia",
    "Khodam Hydra Kekal",
    "Khodam Dragon Naga",
    "Khodam Basilisk Beracun",
    "Khodam Minotaur Kuat",
    "Khodam Yeti Es",
    "Khodam Bigfoot Misterius",
    "Khodam Kraken Lautan",
    "Khodam Chupacabra Tersembunyi",
    "Khodam Wendigo Kedinginan",
    "Khodam Kitsune Ceria",
    "Khodam Tanuki Pintar",
    "Khodam Kappa Berair",
    "Khodam Tengu Angin",
    "Khodam Oni Berkepala Tiga",
    "Khodam Raiju Petir",
    "Khodam Kamaitachi Taji",
    "Khodam Bakeneko Licik",
    "Khodam Nue Transformasi",
    "Khodam Komainu Setia",
    "Khodam Kirin Berkilau",
    "Khodam Tsuchigumo Laba-laba",
    "Khodam Jorogumo Cantik",
    "Khodam Tanuki Gemuk",
    "Khodam Okami Suci",
    "Khodam Inugami Setia",
    "Khodam Tanuki Mencuri",
    "Khodam Noppera-bo Wajah Kosong",
    "Khodam Abumi-guchi Pengerat",
    "Khodam Aka Manto Merah",
    "Khodam Ashiarai Yashiki Kaki Raksasa",
    "Khodam Bake-kujira Paus Hantu",
    "Khodam Buruburu Gemetar",
    "Khodam Dorotabo Tani Menyusup",
    "Khodam Funayurei Hantu Laut",
    "Khodam Gasha-dokuro Tengkorak Raksasa",
    "Khodam Hanako-san Toilet",
    "Khodam Hitodama Api Terbang",
    "Khodam Ikiryo Semangat Terpisah",
    "Khodam Jinmenju Pohon Wajah",
    "Khodam Jubokko Pohon Darah",
    "Khodam Kamikiri Seringai",
    "Khodam Kawa-no-kami Dewa Sungai",
    "Khodam Kuchisake-onna Wanita Bermulut Potong",
    "Khodam Mokumokuren Mata Banyak",
    "Khodam Mujina Pemalu",
    "Khodam Namahage Setan Pengusir",
    "Khodam Nurarihyon Kepala Hijau",
    "Khodam Noppera-bo Wajah Kosong",
    "Khodam Nue Transformasi",
    "Khodam Nuppeppo Lempung Gemuk",
    "Khodam Nurarihyon Kepala Hijau",
    "Khodam Oboroguruma Kereta Hantu",
    "Khodam Odoro-odoro Odoro-odoro",
    "Khodam Ohaguro-bettari Pahatan Gigi Hitam",
    "Khodam Okiku Ningyou Boneka",
    "Khodam Oshiroi Baba Nyonya Berpakaian Putih",
    "Khodam Rokuro-kubi Kepala Terpisah",
    "Khodam Satori Pemikiran",
    "Khodam Shichinin Misaki Pengganggu",
    "Khodam Shikigami Hantu Tertawa",
    "Khodam Tanuki Menjadi Diri Sendiri",
    "Khodam Tengu Berburu",
    "Khodam Tsuchigumo Laba-laba",
    "Khodam Umibozu Perompak Lautan",
    "Khodam Wanyuudou Roda Hantu",
    "Khodam Yama-uba Raksasa Gunung",
    "Khodam Yurei Hantu Sedih",
    "Khodam Zashiki-warashi Setan Kecil",
    "Khodam Yama-uba Raksasa Gunung",
    "Khodam Nurarihyon Kepala Hijau",
    "Khodam Noppera-bo Wajah Kosong",
    "Khodam Nue Transformasi",
    "Khodam Nuppeppo Lempung Gemuk",
    "Khodam Nurarihyon Kepala Hijau",
    "Khodam Oboroguruma Kereta Hantu",
    "Khodam Odoro-odoro Odoro-odoro",
    "Khodam Ohaguro-bettari Pahatan Gigi Hitam",
    "Khodam Okiku Ningyou Boneka",
    "Khodam Oshiroi Baba Nyonya Berpakaian Putih",
    "Khodam Rokuro-kubi Kepala Terpisah",
    "Khodam Satori Pemikiran",
    "Khodam Shichinin Misaki Pengganggu",
    "Khodam Shikigami Hantu Tertawa",
    "Khodam Tanuki Menjadi Diri Sendiri",
    "Khodam Tengu Berburu",
    "Khodam Tsuchigumo Laba-laba",
    "Khodam Umibozu Perompak Lautan",
    "Khodam Wanyuudou Roda Hantu",
    "Khodam Yama-uba Raksasa Gunung",
    "Khodam Yurei Hantu Sedih",
    "Khodam Zashiki-warashi Setan Kecil",
];
await conn.reply(m.chat, `Khodam yang ada di dalam diri *${await conn.getName(who)}* adalah *${await pickRandom(khodam)}*.`, m, {contextInfo: {mentionedJid: [who]}})
}
handler.help = handler.command = ["cekkhodam"]
handler.tags = ["fun"]

module.exports = handler 

function pickRandom(list) {
    return list[Math.floor(list.length * Math.random())]
}